### ISSUE TITLE
Ajout de champs lieu et heure de départ

### ISSUE THREAD

**Issue by matoDL** [Iles-Asma/goteamgo#22]
Ajouter des champs "lieu" sous forme d'adresse et "heureDepart" sur la réservation d'une voiture et la création d'une annonce.

- [x] Ajout du champs "lieu" sur la #8  
- [x] Ajout du champs "heureDepart" sur la #8 
- [x] Afficher ces champs sur la réservation d'une voiture #10 #11 

Tests d'acceptation:

1.  En tant qu'utilisateur, je peux ajouter un champ "lieu" sous forme d'adresse lors de la réservation d'une voiture.

    - Le champ "lieu" est visible sur l'interface de réservation d'une voiture.
    - Je peux saisir une adresse dans le champ "lieu".
    - L'adresse saisie est correctement enregistrée lors de la réservation.
2.  En tant qu'utilisateur, je peux ajouter un champ "heureDepart" lors de la réservation d'une voiture.

    - Le champ "heureDepart" est visible sur l'interface de réservation d'une voiture.
    - Je peux sélectionner une heure de départ dans le champ "heureDepart".
    - L'heure de départ sélectionnée est correctement enregistrée lors de la réservation.
3.  En tant qu'utilisateur, je peux voir les champs "lieu" et "heureDepart" sur l'interface de réservation d'une voiture.

    - Les champs "lieu" et "heureDepart" sont visibles sur l'interface de réservation d'une voiture.
    - Les valeurs saisies pour ces champs lors de la réservation sont affichées correctement.
